### ISSUE TITLE
ImportError: DLL load failed while importing binaryninjaui: The specified module could not be found. Python plugin 'banjo' could not be loaded

### ISSUE THREAD

**Issue by FreedomLabsIO** [CarveSystems/banjo#30]
```
Traceback (most recent call last):
  File "C:\Users\Myself\AppData\Roaming\Binary Ninja\plugins\banjo\__init__.py", line 10, in <module>
    from binaryninjaui import UIContextNotification, UIContext  # type: ignore
  File "E:\binaryNinja2.1\BinaryNinja-personal-2.0.2097-dev\plugins\..\python3\binaryninjaui\__init__.py", line 5, in <module>
    from .binaryninjaui import *
ImportError: DLL load failed while importing binaryninjaui: The specified module could not be found.
Python plugin 'banjo' could not be loaded
```
Python 3.8 is installed

How to fix this?

**Comment by austin-ralls-cs** [comment]
It looks like you're using an old Binary Ninja version. I'd try either
1. Update to a version that has this commit https://github.com/Vector35/binaryninja-api/commit/0de53b97ef6cec57ab4bdfbb9a9e1b6503eecfab
2. Or if you don't have a license to update anymore, roll back a couple commits and use https://github.com/CarveSystems/banjo/commit/c2539554e2f128a4adab6e3c939e61e58e96b3d7
