### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by austin-ralls-cs** [CarveSystems/banjo#5]
There are some Python unittest classes for low-level tests. Somewhere along the line in code reorganization they stopped working.

```
ImportError: Failed to import test module: dex
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/.../.binaryninja/plugins/banjo/android/dex.py", line 9, in <module>
    from .smali import (
ImportError: attempted relative import with no known parent package
```

**Comment by austin-ralls-cs** [comment]
Fixed in https://github.com/CarveSystems/banjo/commit/20639aecf4de68e9f4881655f6fafa9b2e1450c2 by documenting how to run them
